### ISSUE TITLE
Feat: Add support for tags that don't have the 'v' prefix

### ISSUE THREAD

**Issue by lviana-menlosecurity** [pact-foundation/absolute-version-js#1]
The absolute-version package uses the git-describe package, and if no match string is passed (which is what absolute-version seems to do when it calls gitDescribeSync with no parameters), by default only tags that start with a ‘v’ followed by a digit are found:
https://github.com/tvdstaaij/node-git-describe/blob/master/lib/git-describe.js#L28
Now, if you look at [semver](https://semver.org/#is-v123-a-semantic-version), the ‘v’ prefix is not really part of the semantic version:

> Is "v1.2.3" a semantic version?
> No, "v1.2.3" is not a semantic version. However, prefixing a semantic version with a "v" is a common way (in English) to indicate it is a version number. Abbreviating "version" as "v" is often seen with version control. Example: git tag v1.2.3 -m "Release version 1.2.3", in which case "v1.2.3" is a tag name and the semantic version is "1.2.3".

We don’t really use the ‘v’ prefix, and as a result our absolute-version doesn’t really give us what we want:
```
$ git describe
2.80.0-13-85-gecb98756d
$ node node_modules/\@pact-foundation/absolute-version/dist/bin/absolute-version-from-git-tag.js
cb98756d-devlvianatrunkpact+cb98756d
```
If I were to remove the ‘v’ from the match in the git-describe it would give us what we want:
```
$ git describe --always --match v[0-9]*
ecb98756d
$ git describe --always --match [0-9]*
2.80.0-13-85-gecb98756d
```
It would be nice if absolute-version could use the gitDescribeSync overload that has the options parameter, and used a match in which the ‘v’ prefix was optional, but the match is actually a glob, not a regex, so making something optional like that might not be so easy. Alternatively, absolute-version could expose an overload of gitDescribeSync that does take the options parameter.

**Comment by TimothyJones** [comment]
Thanks very much for reporting this! I've released 0.0.3 which has the ability to specify the tag glob:

```
npx @pact-foundation/absolute-version --tagGlob '[0-9]*'
```

You can also specify via the API if you want to go that route. Details are in the readme.

Are you able to share what tools you're using to tag the releases? I went with tags prefixed with `v` because that's the default in `standard-version` and `semantic-release`, which are the two main tools I'm aware of. 

I'd like to have a section in the docs that says "if you're using X tools, use these options, and Y tools use these options" (...or maybe it could even have a helpful default that reads the package.json and sets appropriately.... hmm).
